# Application
spring.application.name=whichbin-api

# Server
server.address=0.0.0.0
server.port=${PORT:5000}
server.servlet.context-path=/api

# Client
app.client-url=${CLIENT_URL:http://localhost:7000}

# Database
# Added "allowPublicKeyRetrieval=true" to allow Spring Boot 4.1.1/Java 21 to connect to
# the mySQL database for tests
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/whichbin_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Web API
spring.web.error.include-stacktrace=never

# Auth
app.auth.token-ttl=${AUTH_TOKEN_TTL:PT24H}
app.auth.token-cleanup-cron=${AUTH_TOKEN_CLEANUP_CRON:0 0 3 * * *}